// OLD_API/packages/widgets/src/solid/tooltip.tsx
import { createSignal, onCleanup } from '@argui/solid'
import type { JSX } from '@argui/solid/jsx-runtime'
import { createSurfaceActivity, type SurfaceTooltipProps } from '../shared/surface-c'

export type TooltipProps = SurfaceTooltipProps<JSX.Element, JSX.Element>

/** Shows a themed tooltip while its trigger is hovered or focused. */
export function Tooltip(props: TooltipProps): JSX.Element {
  const [localOpen, setLocalOpen] = createSignal(props.defaultOpen ?? false)
  const opened = () => props.open ?? localOpen()
  const requestOpen = (value: boolean) => {
    if (opened() === value) return
    if (props.open === undefined) setLocalOpen(value)
    props.onOpenChange?.(value)
  }
  const activity = createSurfaceActivity(requestOpen, 0, 140)
  onCleanup(() => activity.dispose())
  const width = Number.isFinite(props.width) && (props.width ?? 0) > 0 ? props.width! : 220
  const popupKey = `${props.id}-tooltip`
  return <>
    <focusScope key={props.id} role="generic" described_by={opened() ? popupKey : undefined}
      focus_on_tab_navigation={false} onFocus={activity.focusEnter} onBlur={activity.focusLeave}>
      <touchArea key={`${props.id}-tooltip-trigger`} enabled={true}
        onPointerEnter={activity.triggerEnter} onPointerLeave={activity.triggerLeave}>
        {props.children}
      </touchArea>
    </focusScope>
    {opened() ? <popupWindow key={popupKey} anchor={props.id} placement={props.placement ?? 'top'}
      width={width} window_layer="popover" dismiss_policy="outside_pointer_or_escape"
      containment="none" restore_focus={false} role="tooltip"
      accessible_name={props.description} onDismiss={activity.dismiss}>
      <touchArea key={`${popupKey}-hover`} enabled={true} mouse_cursor="default"
        onPointerEnter={activity.contentEnter} onPointerLeave={activity.contentLeave}>
        <rectangle width={width} background={props.theme.foreground} border_color={props.theme.foreground}
          border_width={1} radius={props.theme.controlRadius}
          shadow_blur={props.theme.overlayShadowBlur} shadow_offset_y={3} shadow_color={props.theme.overlayShadow}>
          <column width="fill" padding={props.theme.controlPadding}>{props.content}</column>
        </rectangle>
      </touchArea>
    </popupWindow> : null}
  </>
}

// packages/widgets/src/solid/tooltip.tsx
import { createSignal, createUniqueId } from 'solid-js'
import type { JSX } from '@argui/solid/jsx-runtime'
import { useTheme } from '@argui/solid'
import type { WidgetTheme } from '../shared/theme'
import type { TooltipOptions } from '../shared/types'

/** Props for the native Solid Tooltip. Children form its hover trigger. */
export type TooltipProps = TooltipOptions & { children: JSX.Element }

/** Shows short information beside a hovered or focused trigger. */
export function Tooltip(props: TooltipProps): JSX.Element {
  const id = props.id ?? `argui-tooltip-${createUniqueId()}`
  const popupId = `${id}-popup`
  const theme = useTheme<WidgetTheme>()
  const [open, setOpen] = createSignal(false)

  return <focusScope width={props.width} height={props.height}
    minWidth={props.minWidth} maxWidth={props.maxWidth} minHeight={props.minHeight} maxHeight={props.maxHeight}
    grow={props.grow} shrink={props.shrink} alignSelf={props.alignSelf} margin={props.margin}
    focusable={true} focusOnTabNavigation={true} accessibleDescription={props.content} describedBy={popupId}
    onFocus={() => setOpen(true)} onBlur={() => setOpen(false)}>
    <touchArea id={id} onPointerEnter={() => setOpen(true)}>{props.children}</touchArea>
    {open() ? <popupWindow id={popupId} anchor={id} role="tooltip" accessibleName={props.content}
      placement={props.placement ?? 'top'} width={props.contentWidth ?? 220}
      windowLayer="popover" dismissPolicy="outsideHoverOrEscape"
      containment="none" initialFocus="" restoreFocus={false}
      allowOutsideWindow={props.allowOutsideWindow} onDismiss={() => setOpen(false)}>
      <rectangle padding={{ top: 7, bottom: 7, start: 10, end: 10 }}
        background={props.opaque ? theme().surface : theme().overlaySurface}
        backdropFilter={!props.opaque && props.blur !== false ? `blur(${theme().overlayBlur}px)` : undefined}
        border={{ width: theme().overlayBorderWidth, color: theme().border }}
        radii={theme().overlayRadius}
        shadow={props.allowOutsideWindow ? undefined : { offsetY: theme().overlayShadowOffsetY, blur: theme().overlayShadowBlur, color: theme().overlayShadowColor }}>
        <text color={theme().text} fontSize={14} weight={500}>{props.content}</text>
      </rectangle>
    </popupWindow> : null}
  </focusScope>
}
