// packages/widgets/src/solid/switch.tsx
import { createSignal } from 'solid-js'
import type { JSX } from '@argui/solid/jsx-runtime'
import { useTheme } from '@argui/solid'
import type { WidgetTheme } from '../shared/theme'
import type { BooleanControlOptions } from '../shared/new-controls'

/** Props for a native switch with local or controlled state. */
export type SwitchProps = BooleanControlOptions & { size?: 'default' | 'sm' }

/** Renders a switch with one focusable hit target and a themed track and thumb. */
export function Switch(props: SwitchProps): JSX.Element {
  const theme = useTheme<WidgetTheme>()
  const [localValue, setLocalValue] = createSignal(props.defaultValue ?? false)
  const checked = () => props.value ?? localValue()
  const readOnly = () => props.value !== undefined && !props.onValueChange
  const enabled = () => !props.disabled && !readOnly()
  const small = () => props.size === 'sm'
  const toggle = () => {
    if (!enabled()) return
    const next = !checked()
    if (props.value === undefined) setLocalValue(next)
    props.onValueChange?.(next)
  }
  return <focusScope id={props.id} role="switch" accessibleName={props.accessibleName}
    accessibleDescription={props.description} checkedState={checked() ? 'checked' : 'unchecked'}
    enabled={enabled()} readOnly={readOnly()} keyboardActivation="enterOrSpace" onClick={toggle}
    mouseCursor={enabled() ? 'pointer' : 'notAllowed'}
    width={props.width} minWidth={props.minWidth} maxWidth={props.maxWidth}
    grow={props.grow} shrink={props.shrink} alignSelf={props.alignSelf} margin={props.margin}>
    <row gap={8} alignItems="center">
      <rectangle width={small() ? 24 : 32} height={small() ? 14 : 18} radii={9} shrink={0}
        padding={1} background={checked() ? theme().primary : theme().input}
        hoverBackground={checked() ? theme().primaryHover : theme().controlHover}
        focusBorderColor={theme().focusRing} opacity={enabled() ? 1 : 0.5}>
        <container width="100%" height="100%" position="relative">
          <container width={small() ? 12 : 16} height={small() ? 12 : 16} position="absolute"
            inset={{ start: 0, top: 0 }} transform={{ translateX: checked() ? (small() ? 10 : 14) : 0 }}
            transitionMs={150} transitionTimingFunction="cubic-bezier(0.4, 0, 0.2, 1)">
            <rectangle width="100%" height="100%" radii={8}
              background={checked() ? theme().primaryForeground : theme().background} />
          </container>
        </container>
      </rectangle>
      {props.label ? <text color={theme().text}>{props.label}</text> : null}
    </row>
  </focusScope>
}

// OLD_API/packages/widgets/src/solid/switch.tsx
import { createSignal } from '@argui/solid'
import type { JSX } from '@argui/solid/jsx-runtime'
import type { SwitchProps } from '../shared/foundation-e'

const mobile = (globalThis as { __arguiMobile?: boolean }).__arguiMobile === true

/** Provides a themed native switch with controlled and default-checked state. */
export function Switch(props: SwitchProps): JSX.Element {
  const [uncontrolled, setUncontrolled] = createSignal(props.defaultChecked ?? false)
  const [focused, setFocused] = createSignal(false)
  const [hovered, setHovered] = createSignal(false)
  let pointerFocus = false
  const checked = () => props.checked ?? uncontrolled()
  const disabled = () => !!props.disabled
  const toggle = () => {
    if (disabled()) return
    const next = !checked()
    if (props.checked === undefined) setUncontrolled(next)
    props.onCheckedChange?.(next)
  }
  const small = props.size === 'sm'
  const width = small ? 24 : 32
  const height = small ? 14 : 18
  const thumb = small ? 10 : 14

  return <focusScope key={props.id} role="switch" accessible_name={props.label}
    checked_state={checked() ? 'checked' : 'unchecked'} enabled={!disabled()}
    keyboard_activation="enter_or_space" onClick={toggle}
    onFocus={() => { if (!pointerFocus) setFocused(true) }}
    onKey={() => { pointerFocus = false; setFocused(true) }}
    onBlur={() => { pointerFocus = false; setFocused(false) }}>
    <touchArea enabled={!disabled()} mouse_cursor={disabled() ? 'not_allowed' : 'pointer'}
      onPointerEnter={() => { if (!mobile) setHovered(true) }}
      onPointerLeave={() => setHovered(false)}
      onPointerDown={() => { pointerFocus = true; setFocused(false) }}>
      <rectangle width={width} height={height} radius={height / 2}
        background={checked() ? props.theme.accent : hovered() ? props.theme.surfaceHover : props.theme.surfaceRaised}
        border_color={focused() ? props.theme.accent : props.theme.border}
        border_width={focused() ? 2 : 1} opacity={disabled() ? 0.48 : 1}>
        <row width="fill" height="fill" padding={2} align_items="center">
          {checked() ? <container grow={1} /> : null}
          <rectangle width={thumb} height={thumb} radius={thumb / 2}
            background={checked() ? props.theme.accentText : props.theme.surface} />
          {checked() ? null : <container grow={1} />}
        </row>
      </rectangle>
    </touchArea>
  </focusScope>
}
